version: '3.7'
services:
  postgres:
    container_name: formulaone
    image: postgres:latest
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "functionalformulaone"
    networks:
      - internal
  functional-formula-one-web:
    container_name: functional-formula-one-web
    image: 'functional-formula-one-web:latest'
    ports:
      - '8100:8080'
    environment:
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://formulaone:5432/functionalformulaone
    networks:
      - internal
    depends_on:
      - postgres
networks:
  internal:
